# Generated by Django 4.1.7 on 2023-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam_and_baby_care_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profilePic',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
